/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'projects-list': RouteRecordInfo<'projects-list', '/browse', Record<never, never>, Record<never, never>>,
    'view-project': RouteRecordInfo<'view-project', '/browse/project/:projectId', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'view-track': RouteRecordInfo<'view-track', '/tracks/:trackId', { trackId: ParamValue<true> }, { trackId: ParamValue<false> }>,
    'view-track-version': RouteRecordInfo<'view-track-version', '/tracks/:trackId/:md5', { trackId: ParamValue<true>, md5: ParamValue<true> }, { trackId: ParamValue<false>, md5: ParamValue<false> }>,
  }
}
